channels:
  - defaults
dependencies:
  - backcall=0.1.0
  - blas=1.0
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.3.2
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2019.1
  - ipykernel=5.1.0
  - ipython=7.3.0
  - ipython_genutils=0.2.0
  - jedi=0.13.3
  - jpeg=9b
  - jupyter_client=5.2.4
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.36
  - libsodium=1.0.16
  - libstdcxx-ng=8.2.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - matplotlib=3.0.3
  - mkl=2019.1
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - ncurses=6.1
  - numpy=1.16.2
  - numpy-base=1.16.2
  - openssl=1.1.1b
  - pandas=0.24.2
  - parso=0.3.4
  - pcre=8.43
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pip=19.0.3
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - pygments=2.3.1
  - pyparsing=2.3.1
  - pyqt=5.9.2
  - python=3.6.8
  - python-dateutil=2.8.0
  - pytz=2018.9
  - pyzmq=18.0.0
  - qt=5.9.7
  - readline=7.0
  - scipy=1.2.1
  - setuptools=40.8.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.27.2
  - tk=8.6.8
  - tornado=6.0.1
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - wheel=0.33.1
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
  - pip:
    - attrs==19.1.0
    - beautifulsoup4==4.7.1
    - bleach==3.1.0
    - bs4==0.0.1
    - cerberus==1.2
    - cypy==0.2.0
    - defusedxml==0.5.0
    - entrypoints==0.3
    - gitdb2==2.0.5
    - gitpython==2.1.11
    - jinja2==2.10
    - jsonschema==3.0.1
    - lxml==4.3.2
    - markupsafe==1.1.1
    - mistune==0.8.4
    - nbconvert==5.4.1
    - nbformat==4.4.0
    - pandocfilters==1.4.2
    - pyrsistent==0.14.11
    - quantities==0.12.1
    - git+https://github.com/scidash/sciunit@256b4a7a19149fceb643a6bfd53f4282991d02a8#egg=sciunit
    - smmap2==2.0.5
    - soupsieve==1.8
    - testpath==0.4.2
    - webencodings==0.5.1


