name: ldmunit
channels:
  - defaults
  - conda-forge
  - powerai
  - anaconda
  - r
dependencies:
  - python=3.6.8
  - ipykernel=5.1.0
  - pandas=0.24.2
  - numpy=1.16.2
  - scipy=1.2.1
  - matplotlib=3.0.3
  - oct2py=5.0.2
  - rpy2=2.9.4
  - tzlocal
  - gym
    #- r-rcpp
    #- r-rcppeigen
    #- r-rstan
    #- r-data.table
  - zlib
  - pystan
  - sphinx
  - sphinx_rtd_theme
  - m2r
  - twine
  - pip=9.0.3
  - pip:
   #- hbayesdm
    - git+https://github.com/scidash/sciunit@256b4a7a19149fceb643a6bfd53f4282991d02a8#egg=sciunit
    - black
    - overrides
    - pre-commit
