name: ldmunit
channels:
  - defaults
  - conda-forge
  - hcc
  - anaconda
dependencies:
  - numpy=1.16.2
  - scipy=1.2.1
  - pandas=0.24.2
  - python=3.6.8
  - gym
  - pip
  - pip:
    - git+https://github.com/scidash/sciunit@256b4a7a19149fceb643a6bfd53f4282991d02a8#egg=sciunit
